/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package austpms;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tahmid
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    /***************for storing expire ID and Date temporarily*************/
    // we have to store this in database, if we want to use later those expired
    // id. we have to make a system that a person can warning of date expiring(SMS)
    ArrayList<String> expireID = new ArrayList<String>();
    ArrayList<String> expireIDDate = new ArrayList<String>();
    JFrame expireFrame;
    
    public Home() {
        initComponents();
        screenShowing();
        
        /*checking expired id*/
        idGetExpired();
        
        //call update sem while open
        updateSemesterStatus();
    }
    
    
    private void screenShowing(){
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        //setSize(size.width/2, size.height/2 + 100);
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    
    private void updateSemesterStatus(){
        ConnectDatabase db = new ConnectDatabase();
        db.ConnectDB();
        Time time = new Time();
        String currentDate = time.getCurrentDate();
        db.updateSemesterCurrentStatus(currentDate);
        db.updateSemesterPrevStatus(currentDate);
    }
    
    // a function to find and show the IDs, expired validity for AUST PMS in a table form
    private void idGetExpired(){
        Time time = new Time();
        String curDate = time.getCurrentDate();
//        System.out.println(curDate);
        try{
            ConnectDatabase conDatabase = new ConnectDatabase();
            conDatabase.ConnectDB();
            conDatabase.checkingExpireDate(curDate);
            while(conDatabase.getExtraResultSet().next()){
                expireID.add(conDatabase.getExtraResultSet().getString("ID"));
                expireIDDate.add(conDatabase.getExtraResultSet().getString("ExpiryDate"));
            }
            if(expireID == null){
                expireID.add("no one");
            }
        }catch(Exception e)
        {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
        
//        for(int i=0; i<expireID.size(); i++){
//            System.out.println(expireID.get(i));
//        }
        
        expireFrame = new JFrame();
        expireFrame.setSize(400, 400);
        //expireFrame.setLayout(null);
        expireFrame.setResizable(false);
        expireFrame.setTitle("Expired List For Parking");

        /**********************table create**************************/
        JTable table = new JTable();
        table.setModel(new DefaultTableModel(null, new Object[]{"Expire Id", "Expire Date"}));
        table.setBounds(0,50,300,300);
        JScrollPane sp=new JScrollPane(table);
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        for(int i = 0; i<expireID.size(); i++){
            model.insertRow(model.getRowCount(), new Object[]{expireID.get(i),expireIDDate});
        }
        
        /***************expire frame setting***************/
        expireFrame.add(sp);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        expireFrame.setLocation(size.width/3 - getWidth()/2-100, size.height/2 - getHeight()/2);
        /********start a thread to dispose the expire frame automatically after 10 sec********/
        new Thread(new Runnable(){
            public void run(){
                try{
                    Thread.sleep(10000);
                    expireFrame.dispose();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }).start();
        /********end of thread to dispose the expire frame automatically after 10 sec********/
        expireFrame.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        databaseButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        semesterButton = new javax.swing.JButton();
        regNewVehicle = new javax.swing.JButton();
        parkingStatusButton = new javax.swing.JButton();
        expandButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUST Parking Management System");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 50, -1, 130));

        databaseButton.setBackground(new java.awt.Color(0, 255, 153));
        databaseButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        databaseButton.setForeground(new java.awt.Color(255, 255, 255));
        databaseButton.setText("Database");
        databaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(databaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 40));

        registerButton.setBackground(new java.awt.Color(0, 255, 153));
        registerButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 40));

        semesterButton.setBackground(new java.awt.Color(0, 255, 153));
        semesterButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        semesterButton.setForeground(new java.awt.Color(255, 255, 255));
        semesterButton.setText("Semester");
        semesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(semesterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 40));

        regNewVehicle.setBackground(new java.awt.Color(0, 255, 153));
        regNewVehicle.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regNewVehicle.setForeground(new java.awt.Color(255, 255, 255));
        regNewVehicle.setText("Register New Vehicle");
        regNewVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNewVehicleActionPerformed(evt);
            }
        });
        jPanel1.add(regNewVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 200, 30));

        parkingStatusButton.setBackground(new java.awt.Color(0, 255, 153));
        parkingStatusButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parkingStatusButton.setForeground(new java.awt.Color(255, 255, 255));
        parkingStatusButton.setText("Parking Status");
        parkingStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkingStatusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(parkingStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 30));

        expandButton.setBackground(new java.awt.Color(0, 255, 153));
        expandButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expandButton.setForeground(new java.awt.Color(255, 255, 255));
        expandButton.setText("Expand Validation");
        expandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandButtonActionPerformed(evt);
            }
        });
        jPanel1.add(expandButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Parking Management System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel3.setText("PMS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo(small).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/homeBg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 720, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Transaction tr = new Transaction();
        tr.setVisible(true);
        expireFrame.dispose();
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void databaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Database database = new Database();
        database.setVisible(true);
        expireFrame.dispose();
        
    }//GEN-LAST:event_databaseButtonActionPerformed

    private void regNewVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNewVehicleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RegisterNewVehicle regNew = new RegisterNewVehicle();
        regNew.setVisible(true);
        expireFrame.dispose();
    }//GEN-LAST:event_regNewVehicleActionPerformed

    private void parkingStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkingStatusButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ParkingStatus parkingStatus = new ParkingStatus();
        parkingStatus.setVisible(true);
        expireFrame.dispose();
    }//GEN-LAST:event_parkingStatusButtonActionPerformed

    private void expandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandButtonActionPerformed
        // TODO add your handling code here:
        expireFrame.dispose();
        
        String id;
        String vehicleNum;
        String newExpiryDate = null;
        
        id = JOptionPane.showInputDialog("Please enter your ID");
        vehicleNum = JOptionPane.showInputDialog("Please enter your Vehicle Number");
        
        if(id != null && vehicleNum != null){
            ConnectDatabase connectDatabase = new ConnectDatabase();
            connectDatabase.ConnectDB();

            connectDatabase.retrieveForExpandDate(id, vehicleNum);
            String profession = connectDatabase.getProfession();

            if(connectDatabase.getId() == null){
                JOptionPane.showMessageDialog(null, "Sorry, your ID is missing.\nMaybe your input is Wrong.\nInput again");
            }
            else{
                Time time = new Time();
                String curDate = time.getCurrentDate();
                String splitDate[] = curDate.split("-", 3);

                int date = Integer.parseInt(splitDate[2]);
                int month = Integer.parseInt(splitDate[1]);
                int year = Integer.parseInt(splitDate[0]);
                int expireIn;
                int extendMonth = 0;
                int extendYear = 0;
                if(profession.equals("Student")){
                    connectDatabase.ConnectDB();
                    String endDate = connectDatabase.retrieveSemesterInfo("current");
                
                    newExpiryDate = endDate;
                    connectDatabase.CloseDB();
                }
                else if(profession.equals("Teacher") || profession.equals("Staff")){
                    expireIn = 1;
                    extendYear = year + expireIn;

                    newExpiryDate = String.valueOf(extendYear) + "-" + String.valueOf(month) + "-" + String.valueOf(date);
                }
                //database e update korte hobe(just update method ta call korte hobe)
                JOptionPane.showMessageDialog(null, "Thank you.\nYour data have been updated\nNew expiry date: " + newExpiryDate);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter your ID and Vehicle Number correctly");
        }
    }//GEN-LAST:event_expandButtonActionPerformed

    private void semesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Semester sem = new Semester();
        sem.setVisible(true);
    }//GEN-LAST:event_semesterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton databaseButton;
    private javax.swing.JButton expandButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton parkingStatusButton;
    private javax.swing.JButton regNewVehicle;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton semesterButton;
    // End of variables declaration//GEN-END:variables
}
