/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package austpms;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tahmid
 */
public class RegisterNewVehicle extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewVehicle
     */
    
    
    //variables
    private boolean profileActiveState = false;
    private int charCountForVehicleNum = 0;
    
    private String profession = null;
    
    public RegisterNewVehicle() {
        initComponents();
        screenShowing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void screenShowing(){
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        //setSize(size.width/2, size.height/2 + 100);
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
    }
    
    private void enableField(boolean state){
        typeCombo.setEnabled(state);
        serialCombo.setEnabled(state);
        
        modelField.setEnabled(state);
        colorField.setEnabled(state);
        numField.setEnabled(state);
        regDateField.setEnabled(state);
        expDateField.setEnabled(state);
    }
    
    private void defaultValue(){
        nameLabel.setText("Name");
        idLabel.setText("ID");
        professionLabel.setText("Profession");
        deptLabel.setText("Department");
        vehicleLabel.setText("Number of Vehicle");
        
        imageLabel.setIcon(null);
        imageLabel.setText("Image");
        
        profileActiveState = false;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        idSubmit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        professionLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        vehicleLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        serialCombo = new javax.swing.JComboBox<>();
        expDateField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        numField = new javax.swing.JTextField();
        regDateField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AUST Parking Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 30, -1));

        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idField.setText("Please enter your ID");
        idField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idFieldMouseClicked(evt);
            }
        });
        jPanel2.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 240, -1));

        idSubmit.setBackground(new java.awt.Color(0, 255, 204));
        idSubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idSubmit.setText("OK");
        idSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(idSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 130, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 770, 10));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Profile");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 1, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 36, 97, 10));

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));
        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        imageLabel.setText("Image");
        imagePanel.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        jPanel1.add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, 170));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, -1));

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLabel.setText("ID");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, -1));

        professionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        professionLabel.setText("Profession");
        jPanel1.add(professionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, -1));

        deptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deptLabel.setText("Department");
        jPanel1.add(deptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 310, -1));

        vehicleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        vehicleLabel.setText("Number of Vehicles");
        jPanel1.add(vehicleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 310, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 330, 380));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Expiry Date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Vehicle Type");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Vehicle Model");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Vehicle Color");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Vehicle Serial");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Vehicle Number");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Registration Date");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        typeCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Car", "Self Driving Car", "Motor Bike" }));
        typeCombo.setEnabled(false);
        jPanel2.add(typeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 210, -1));

        serialCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serialCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Ha", "La", "Ga", "Gha", "Ka" }));
        serialCombo.setEnabled(false);
        jPanel2.add(serialCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 210, -1));

        expDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        expDateField.setEnabled(false);
        expDateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expDateFieldMouseClicked(evt);
            }
        });
        jPanel2.add(expDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 210, -1));

        modelField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelField.setEnabled(false);
        jPanel2.add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 210, -1));

        colorField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colorField.setEnabled(false);
        jPanel2.add(colorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 210, -1));

        numField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numField.setEnabled(false);
        numField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numFieldKeyTyped(evt);
            }
        });
        jPanel2.add(numField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 210, -1));

        regDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        regDateField.setEnabled(false);
        regDateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regDateFieldMouseClicked(evt);
            }
        });
        jPanel2.add(regDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 210, -1));

        backButton.setBackground(new java.awt.Color(0, 255, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        submitButton.setBackground(new java.awt.Color(255, 0, 51));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_parking.jpg"))); // NOI18N
        jPanel2.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFieldMouseClicked
        // TODO add your handling code here:
        idField.setText("");
        enableField(false);
        defaultValue();
    }//GEN-LAST:event_idFieldMouseClicked

    private void regDateFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regDateFieldMouseClicked
        // TODO add your handling code here:
        if(profileActiveState){
            Time time = new Time();
            regDateField.setText(time.getCurrentDate());
        }
    }//GEN-LAST:event_regDateFieldMouseClicked

    private void expDateFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expDateFieldMouseClicked
        // TODO add your handling code here:
        
        if(profileActiveState){
            String profession[] = professionLabel.getText().split(" ", 2);
            if(regDateField.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please click on Registration Date field first");
            }
            else{
                String curDate = regDateField.getText();
                String splitDate[] = curDate.split("-", 3);

                int date = Integer.parseInt(splitDate[2]);
                int month = Integer.parseInt(splitDate[1]);
                int year = Integer.parseInt(splitDate[0]);
                int expireIn;
                int extendMonth = 0;
                int extendYear = 0;
                if(profession[1].equals("Student")){
                    expireIn = 6;
                    extendMonth = month + expireIn;

                    if(extendMonth <= 12){
                        expDateField.setText(String.valueOf(year) + "-" + String.valueOf(extendMonth) + "-" + String.valueOf(date));
                    }
                    else{
                        year = year + 1;
                        extendMonth = extendMonth % 12;
                        expDateField.setText(String.valueOf(year) + "-" + String.valueOf(extendMonth) + "-" + String.valueOf(date));
                    }
                }
                else if(profession[1].equals("Teacher")|| profession.equals("Staff")){
                    expireIn = 1;
                    extendYear = year + expireIn;

                    expDateField.setText(String.valueOf(extendYear) + "-" + String.valueOf(month) + "-" + String.valueOf(date));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please select profession");
                }
            }
        }
    }//GEN-LAST:event_expDateFieldMouseClicked

    private void idSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSubmitActionPerformed
        // TODO add your handling code here:
        String id = null;
        
        if(idField.getText().equals("") || idField.getText().equals("Please enter your ID")){
            JOptionPane.showMessageDialog(null, "Please enter your ID first");
            profileActiveState = false;
        }
        else{
            
//            name = "Tahmid Khandokar";
//            
//            profession = "Teacher";
//            department = "CSE";
//            vehicle = 1;

            id = idField.getText();
            
            ConnectDatabase connectDatabase = new ConnectDatabase();
            connectDatabase.ConnectDB();
            
            connectDatabase.retrieveDataNewVehicle(id);
            
            if(connectDatabase.getId() == null){
                JOptionPane.showMessageDialog(null, "Data not found\nPlease check your ID");
            }else{
            profession = connectDatabase.getProfession();
            nameLabel.setText(connectDatabase.getFirstName() + " " + connectDatabase.getLastName());
            idLabel.setText("ID: " + connectDatabase.getId());
            professionLabel.setText("Profession: " + connectDatabase.getProfession());
            deptLabel.setText("Department: " + connectDatabase.getDepartment());
            vehicleLabel.setText("Number of Vehicle: " + connectDatabase.getCountVehicle());
            
            
            
            /******************set image(covert byte array to ImageIcon*************/
            try{
                byte[] pic = connectDatabase.getPhoto();        
                ImageIcon img = new ImageIcon(pic);
                Image image = img.getImage();
                Image myImg;
                myImg = image.getScaledInstance(imagePanel.getWidth(), imagePanel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImg = new ImageIcon(myImg);
                imageLabel.setText("");
                imageLabel.setIcon(newImg);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Image not found");
            }
                       

            enableField(true);
            profileActiveState = true;
            }
        }
    }//GEN-LAST:event_idSubmitActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:         
        String vehicleType = typeCombo.getSelectedItem().toString();
        String vehicleModel = modelField.getText();
        String vehicleColor = colorField.getText();
        
        String vehicleSerial = serialCombo.getSelectedItem().toString();
        String vehicleNum = numField.getText();
        
        String regDate = regDateField.getText();
        String expDate = expDateField.getText();
        
        
        if(profileActiveState){
            ConnectDatabase connectDatabase = new ConnectDatabase();
            connectDatabase.ConnectDB();  
            
            connectDatabase.storeVehicleData(vehicleSerial, vehicleNum, vehicleType, vehicleModel, vehicleColor, regDate, expDate, idField.getText());
            JOptionPane.showMessageDialog(null, "Data for " + idField.getText() + " is updated");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void numFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numFieldKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(charCountForVehicleNum < 6){
        if(!Character.isDigit(ch)){
            evt.consume();
            
            if(ch == evt.VK_BACK_SPACE || ch == evt.VK_DELETE){
                charCountForVehicleNum--;
                if(charCountForVehicleNum < 0){
                    charCountForVehicleNum = 0;
                }
            }
            else
                getToolkit().beep();
        }
        else{
            charCountForVehicleNum++;
            System.out.println(charCountForVehicleNum);
        }
        }
        else{
            evt.consume();
            if(ch == evt.VK_BACK_SPACE || ch == evt.VK_DELETE){
                charCountForVehicleNum--;
                if(charCountForVehicleNum < 0){
                    charCountForVehicleNum = 0;
                }
            }
            else
                getToolkit().beep();
        }
    }//GEN-LAST:event_numFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNewVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNewVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JTextField expDateField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton idSubmit;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numField;
    private javax.swing.JLabel professionLabel;
    private javax.swing.JTextField regDateField;
    private javax.swing.JComboBox<String> serialCombo;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JLabel vehicleLabel;
    // End of variables declaration//GEN-END:variables
}
